'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property id_usuario As Integer
    Public Property dni_Empleados As Nullable(Of Integer)
    Public Property contraseña As String
    Public Property id_tipoUsuario As Nullable(Of Integer)
    Public Property Estado_usuario As Nullable(Of Boolean)

    Public Overridable Property Empleados As Empleados
    Public Overridable Property tipoUsuario As tipoUsuario

End Class
